# SPDX-License-Identifier: GPL-3.0-or-later
[package]
name         = "sayratd"
description  = "SayRat background daemon: state engine, indexer, and Wasm plugin host."
version      .workspace = true
edition      .workspace = true
license      .workspace = true
repository   .workspace = true
homepage     .workspace = true
authors      .workspace = true
rust-version .workspace = true

[[bin]]
name = "sayratd"
path = "src/main.rs"

[dependencies]
sayrat-protocol = { path = "../sayrat-protocol" }
anyhow          .workspace = true
log             .workspace = true
env_logger      .workspace = true
pico-args       .workspace = true
